sudo: required
dist: bionic

language: cpp

compiler:
    - gcc

addons:
  apt:
    packages:
      - libsnappy-dev
      - liblz4-dev
      - clang-format-3.9
      - libaio-dev
      - libzstd-dev

cache:
    - ccache
    - apt

before_install:
  - python --version
  - pip install -U cmake # use the latest version of cmake

before_script:
    - cd rdsn/thirdparty
    - wget https://github.com/XiaoMi/pegasus-common/releases/download/deps/pegasus-thirdparty-prebuild-bionic.zip
    - unzip pegasus-thirdparty-prebuild-bionic.zip
    - rm -f pegasus-thirdparty-prebuild-bionic.zip
    - cd ../..
    - ulimit -c unlimited -S

script:
    - ./scripts/travis.sh

after_script:
    - ./run.sh stop_zk

notifications:
    email: false
